image: python:3.11      # or any base image with your security tools + Python + jq

pipelines:
  default:
    - step:
        name: Build-Test-Security-Corgea
        caches:
          - pip
        script:
          # ---------- Build & Test ----------
          - apt-get update && apt-get install -y --no-install-recommends make
          - pip install --quiet uv
          - make install          # install dev dependencies via uv
          - make model-de         # pull German spaCy model required by tests
          - make model-it         # pull Italian spaCy model required by tests
          - make lint             # static analysis via ruff
          - make test             # run pytest suite

          # ---------- Security Scan ----------
          # Example using Fortify SAST
          # - sourceanalyzer -b ${BITBUCKET_REPO} -clean
          # - sourceanalyzer -b ${BITBUCKET_REPO} -python-version 3.11 -python-path .venv/lib/python3.11/site-packages inconnu
          # - sourceanalyzer -b ${BITBUCKET_REPO} -scan -f scan.fpr -disable-source-bundling true
          # - corgea upload scan.fpr --project ${BITBUCKET_REPO}
          - corgea scan

          # ---------- Corgea ----------
          - pip install --quiet corgea-cli
          - corgea login ${CORGEA_API_TOKEN}
          - corgea upload scan.fpr --project ${BITBUCKET_REPO}

          # Wait for triage to complete and capture the Scan ID
          - SCAN_ID=$(corgea wait | jq -r '.id')

          # ---------- Retrieve & iterate through issues ----------
          - mkdir -p corgea_issues
          # List ALL issues for this scan, in JSON
          - corgea ls --issues --scan-id "${SCAN_ID}" --json > issues.json
          # Extract each issue ID and loop
          - |
            for ISSUE_ID in $(jq -r '.[].id' issues.json); do
              echo "Fetching details for $ISSUE_ID"
              corgea inspect --issue "$ISSUE_ID" --json > "corgea_issues/${ISSUE_ID}.json"
            done

          # ---------- Code Insights ----------
          # A helper that reads the *.json files and pushes annotations
          - ./scripts/post-code-insights.sh corgea_issues